### ISSUE TITLE
Commit changes to git and push

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#14]
Once a new term has been added (#12) and the file has been saved (#11) we should immediately commit the change to git and push.

The first version can shell out to `git` and assume that it is the only commiter. In the future we should use a JVM implemention of git.

The status page (#13) should indicate git status, and indicate an error on merge conflicts or whatever.

**Comment by inaimathi** [comment]
https://github.com/clj-jgit/clj-jgit exists, and doesn't seem to be too much harder than shelling.

**Comment by jamesaoverton** [comment]
Ok. My main worry is authenticating the push with GitHub. I guess the right way is to get a key from GitHub. Is there anything easier?

**Comment by inaimathi** [comment]
Couple approaches off the top of my head.

1. Set up a separate user account for this application, set up RSA authentication for it, and arrange it so that the appropriate keys are in the right place on the deployment target.

2. Use [github OAuth](https://developer.github.com/v3/oauth/) facilities to authenticate as an existing user (or do the separate user account thing, if you don't want your human users to have github accounts).

Either way we can get authenticated pushes happening into the appropriate storage repo.

**Comment by inaimathi** [comment]
Ok, so.

Implemented git committing the slightly hacky way by shelling out using [conch](https://github.com/Raynes/conch) as part of https://github.com/knocean/knode/commit/0e1725c9bed6d384ea2c6049d8c9b30d3dbd9da2.

1. `clj-jgit` doesn't have `git-push` implemented due to config issues. Those config issues seem to be related to the authentication system.
2. The native `jgit` methods should theoretically work, but `(git/with-identity {:private <slurped private key> :public <slurped public key>} (-> git-repo (.push) (.call)))` fails with a `JSchException USERAUTH fail` (this is related to the above config)

Depending on how strongly we feel about this, we might want to make a contribution to `clj-jgit` to implement that. Unless it's quite strongly, I'll make a note to do it on my own time, but I'm open to looking at this as part of the `knode` project if you like.

If we do end up going down that road, useful resources include

- http://download.eclipse.org/jgit/docs/jgit-2.0.0.201206130900-r/apidocs/org/eclipse/jgit/api/Git.html
- http://clj-jgit.github.io/clj-jgit/
- https://stackoverflow.com/questions/13446842/how-do-i-do-git-push-with-jgit
- https://stackoverflow.com/questions/13686643/using-keys-with-jgit-to-access-a-git-repository-securely
- https://github.com/clj-jgit/clj-jgit/blob/master/src/clj_jgit/porcelain.clj
